//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletTracker.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WalletTracker.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Btn_New {
            get {
                return ResourceManager.GetString("Btn_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string Btn_ViewMore {
            get {
                return ResourceManager.GetString("Btn_ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Wallet.
        /// </summary>
        public static string Lbl_CurrentMonthWallet {
            get {
                return ResourceManager.GetString("Lbl_CurrentMonthWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good day!.
        /// </summary>
        public static string Lbl_Goodday {
            get {
                return ResourceManager.GetString("Lbl_Goodday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available transactions.
        /// </summary>
        public static string Lbl_NoAvailableTransactions {
            get {
                return ResourceManager.GetString("Lbl_NoAvailableTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search any keyword.
        /// </summary>
        public static string Lbl_Placeholder_SearchAnyKeyword {
            get {
                return ResourceManager.GetString("Lbl_Placeholder_SearchAnyKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Lbl_Statistics {
            get {
                return ResourceManager.GetString("Lbl_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expense:.
        /// </summary>
        public static string Lbl_TotalExpense {
            get {
                return ResourceManager.GetString("Lbl_TotalExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Income:.
        /// </summary>
        public static string Lbl_TotalIncome {
            get {
                return ResourceManager.GetString("Lbl_TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Activities.
        /// </summary>
        public static string Lbl_WalletActivities {
            get {
                return ResourceManager.GetString("Lbl_WalletActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Transactions.
        /// </summary>
        public static string Lbl_WalletTransactions {
            get {
                return ResourceManager.GetString("Lbl_WalletTransactions", resourceCulture);
            }
        }
    }
}
